// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"

	port "github.com/rpuggian/ports-service/proto"

	response "github.com/rpuggian/ports-service/api/domain/handlers/response"
)

// PortService is an autogenerated mock type for the PortService type
type PortService struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PortService) FindByID(ctx context.Context, id string) (*response.FindPortResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *response.FindPortResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.FindPortResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.FindPortResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.FindPortResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadPortFile provides a mock function with given fields: ctx, fileStream
func (_m *PortService) UploadPortFile(ctx context.Context, fileStream io.ReadCloser) (*port.CreateResponse, error) {
	ret := _m.Called(ctx, fileStream)

	if len(ret) == 0 {
		panic("no return value specified for UploadPortFile")
	}

	var r0 *port.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.ReadCloser) (*port.CreateResponse, error)); ok {
		return rf(ctx, fileStream)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.ReadCloser) *port.CreateResponse); ok {
		r0 = rf(ctx, fileStream)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.ReadCloser) error); ok {
		r1 = rf(ctx, fileStream)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPortService creates a new instance of PortService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPortService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PortService {
	mock := &PortService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
